### ISSUE TITLE
CI中にisortが正常に動かない

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/.github#170]
**概要**

CI中にisortが正常に動かないトラブルが発生中。

```
Run pip3 install isort
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting isort
  Downloading isort-5.12.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 8.5 MB/s eta 0:00:00
Installing collected packages: isort
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  WARNING: The scripts isort and isort-identify-imports are installed in '/opt/hostedtoolcache/Python/3.8.17/x64/lib/cube_speech' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed isort-5.12.0

Notice:  A new release of pip is available: 23.0.1 -> 23.1.2
Notice:  To update, run: pip install --upgrade pip
/home/runner/work/_temp/0f8ab8fd-63c6-4527-a27f-[13](https://github.com/sbgisen/cube_speech/actions/runs/5516695393/jobs/10058355195?pr=48#step:10:14)c5f09b4588.sh: line 3: isort: command not found
Error: Process completed with exit code 1[27](https://github.com/sbgisen/cube_speech/actions/runs/5516695393/jobs/10058355195?pr=48#step:10:28).
```

https://github.com/sbgisen/cube_speech/actions/runs/5516808104/jobs/10058615105

関連箇所
https://github.com/sbgisen/.github/blob/1fded74a20fac91aad14b70775efba7c79ee3f54/.github/workflows/linter_ros_package.yaml#L118-L122

**Comment by MikhailBertrand** [comment]
よく見ると、flake8も正常にインストールされていない。

```
（略）

Notice:  A new release of pip is available: 23.0.1 -> 23.1.2
Notice:  To update, run: pip install --upgrade pip
--2023-07-12 02:51:53--  https://raw.githubusercontent.com/sbgisen/.github/main/setup.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 1[85](https://github.com/sbgisen/cube_speech/actions/runs/5527028707/jobs/10082369741#step:9:86).199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 904 [text/plain]
Saving to: ‘setup.cfg.1’

     0K                                                       100% 51.3M=0s

2023-07-12 02:51:53 (51.3 MB/s) - ‘setup.cfg.1’ saved [904/904]

/home/runner/work/_temp/64f215a0-[89](https://github.com/sbgisen/cube_speech/actions/runs/5527028707/jobs/10082369741#step:9:90)7b-4bbf-9ca3-0da005316b3b.sh: line 5: flake8: command not found
```

ここもエラー落ちするはずだが、していない模様

**Comment by MikhailBertrand** [comment]
> WARNING: The scripts isort and isort-identify-imports are installed in '/opt/hostedtoolcache/Python/3.8.17/x64/lib/cube_speech' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

@Tacha-S 
ここにisortがインストールされているのは普通ですか？この警告通り、PATHにないのであれば当然のエラー落ちですが

**Comment by Tacha-S** [comment]
最後のlib/cube_speechはいらなさそうですけど、正確にはわからないです

**Comment by MikhailBertrand** [comment]
> `$base/lib/cube_speech` を参照されてそうですか？

というのは何から？

（メモ）
一部の環境変数
```
$GITHUB_ACTION_PATH/script.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib
    INPUT_GITHUB_TOKEN: ***
    INPUT_TOOL_NAME: autopep8
    INPUT_LEVEL: warning
    INPUT_FILTER_MODE: file
    INPUT_FAIL_ON_ERROR: true
    INPUT_REVIEWDOG_FLAGS: 
    INPUT_CLEANUP: true
```
